name: petrolpumdealerchayan
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  flutter_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  flutter_easyloading: ^3.0.5
  fluttertoast: ^8.2.2
  go_router: ^10.0.0

  url_strategy: ^0.2.0
  advanced_datatable: ^0.0.8
  emailjs: ^1.3.0
  http: ^1.1.0
  marquee: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  web:
    generate: true
    image_path: "assets/images/homebanner.jpg"

flutter:
  uses-material-design: true

  assets:
    - assets/images/


  
